### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by salvadorbs** [salvadorbs/Asuite#73]
Some months ago, I decided to use Lazarus + FPC for ASuite. With this move, we can porting the software in Linux. Unfortunately this is not so simple to do. This issue track every bug about this development.

- [x] Trayicon Menu (Classic or Graphic) in GTK2/QT5
- [x] Execute any file/folder
- [x] Icon support (in Linux, it is completely different than Windows)
- [x] Create/delete shortcut asuite item in desktop
- [x] Path (delimeter and similar stuff)
- [x] Add Github action for Linux GTK2, GTK3 and QT5 (64bit)
- [x] Layout forms
- [x] Hotkey in GTK3 (hard, ~~maybe missing pascal bindings to do it~~ In GDK3 binding miss two important methods, so we have two choices: add them in GDK3pas or make pascal binding of KeyBinder) - ~~For now it is disabled in gtk3~~
- [x] Icon extraction using libraries QT or GTK
- [x] Start ASuite at OS startup (see https://github.com/tomboy-notes/tomboy-ng/blob/master/source/autostart.pas)
- [x] Drag&Drop (need more testing)
- [x] Cut, copy & paste operations in VirtualTree

Features disabled in Linux:
- AutoExpansionFolder (only in GTK, in QT5 works!)
- Eject dialog from GraphicMenu

Features modified in Linux:
- Create shortcut in Desktop (in Windows there is .lnk files with path, parameters and working dir, in Linux will be a simple hard link)
- ~~Icon support (need more testing - maybe it is different than windows)~~ Found a way to use widget libraries to extract icon like in Windows (see above)
- Trayicon Options in GTK (libappindicator3 in GTK call directly a context menu)

Target environment desktop
- GTK2
- GTK3 (very unstable)
- QT5

Release date? I don't known, I can say when it is ready.

For commits, you can see the initial pull request https://github.com/salvadorbs/Asuite/pull/72.

**Comment by salvadorbs** [comment]
Useful links
- Trayicon issue in Wayland https://github.com/tomboy-notes/tomboy-ng/issues/216

**Comment by salvadorbs** [comment]
I found a way to add extract icon in Linux (gtk2, gtk3 and qt5), thanks to DoubleCommander and some other research. In these days, I'm working to make a patch for Lazarus 2.2 to add this feature in TShellTreeview and TShellListview. Once the patch is applied, it will be very easy to add this feature in ASuite as well.

**Comment by salvadorbs** [comment]
Given the situation of ASuite development on Linux (and Windows), I decided to release a new (highly unstable) version. Of course there is still work, but I would say it is a great starting point.

Now it is time to start improving the stability of the code and therefore I will close this development issue. Thanks!
